export enum RightsCode {
  REGISTER_USER = 'REGISTER_USER',
  EDIT_PROFILE = 'EDIT_PROFILE',
  EDIT_ROLES = 'EDIT_ROLES',
  DELETE_USER = 'DELETE_USER',
  CREATE_CORRESPONDENT = 'CREATE_CORRESPONDENT',
  EDIT_CORRESPONDENT = 'EDIT_CORRESPONDENT',
  DELETE_CORRESPONDENT = 'DELETE_CORRESPONDENT',
  VIEW_USERS = 'VIEW_USERS',
  EDIT_PASSWORD = 'EDIT_PASSWORD',
  VIEW_STATISTICS = 'VIEW_STATISTICS',
  VIEW_MESSAGES = 'VIEW_MESSAGES',
  SERVICE_CONSUMER = 'SERVICE_CONSUMER',
}

export interface Right {
  id: number;
  name: string;
  code: RightsCode;
}
